name: Memory leak checker
on: [push]
permissions:
  contents: read
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:

      - name: Checkout Tcl
        uses: actions/checkout@v4
        with:
          repository: tcltk/tcl
          ref: core-8-6-14
          path: tcl
      - name: Configure Tcl
        working-directory: tcl/unix
        run: |
          ./configure --enable-symbols=all --prefix=$HOME/tcl_install || {
            cat config.log
            echo "::error::Failure during Configure Tcl"
            exit 1
          }
      - name: Build Tcl
        working-directory: tcl/unix
        run: |
          make -j || {
            echo "::error::Failure during Build Tcl"
            exit 1
          }
      - name: Install Tcl
        working-directory: tcl/unix
        run: |
          make install || {
            echo "::error::Failure during Install Tcl"
            exit 1
          }

      - name: Checkout libvalkey
        uses: actions/checkout@v4
        with:
          repository: valkey-io/libvalkey
          ref: main
          path: libvalkey
      - name: Configure libvalkey
        working-directory: libvalkey
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/libvalkey -DCMAKE_PREFIX_PATH=$HOME/libvalkey -DENABLE_SSL=OFF
      - name: Build libvalkey
        working-directory: libvalkey/build
        run: |
          make -j || {
            echo "::error::Failure during Build libvalkey"
            exit 1
          }
      - name: Install libvalkey
        working-directory: libvalkey/build
        run: |
          make install || {
            echo "::error::Failure during Install libvalkey"
            exit 1
          }

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Configure
        run: |
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=$HOME/libvalkey -DCMAKE_PREFIX_PATH=$HOME/libvalkey -DTCL_INCLUDE_DIR=$HOME/tcl_install/include -DTCL_LIBRARY_DIR=$HOME/tcl_install/lib
      - name: Build
        working-directory: build
        run: |
          make -j || {
            echo "::error::Failure during Build"
            exit 1
          }
      - name: Run Tests
        working-directory: build
        run: |
          MEMDEBUG=1 make test || {
            echo "::error::Failure during Test"
            exit 1
          }
      - name: Test-Drive Installation
        working-directory: build
        run: |
          make install || {
            echo "::error::Failure during Install"
            exit 1
          }
